name: 'Test and Deploy'

on:
  pull_request:
  push:
    branches: [master]

env:
  REACT_APP_MORALIS_SERVER_URL: ${{ secrets.REACT_APP_MORALIS_SERVER_URL }}
  REACT_APP_MORALIS_APP_ID: ${{ secrets.REACT_APP_MORALIS_APP_ID }}

jobs:
  setup:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn
  test:
    needs: setup
    name: 'Test Smart Contracts'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run Hardhat tests
        run: npx hardhat test
  deploy:
    needs: test
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: CI="" yarn build
      - name: Deploy to netlify prod environment
        if: $GITHUB_REF_NAME == "master"
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=./build --prod -m "${{GITHUB_REF_NAME}} ${{GITHUB_SHA}}"
      - name: Deploy to netlify test environment
        if: $GITHUB_REF_NAME != "master"
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_TEST }}
        with:
          args: deploy --dir=./build --prod -m "${{GITHUB_REF_NAME}} ${{GITHUB_SHA}}"
