name: 'Test'

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    name: 'Test Smart Contracts'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn
      - run: CI="" yarn build
      - name: Run Hardhat tests
        run: npx hardhat test